application: macassassingame  #whole file setting up dependencies
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: application/static

- url: .*
  script: run.application.app
